<?php
/* -------------------------------------------------------------------------------------
* 	ID:				currencies.php
* 	erstellt von:	Daniel Siekiera <danielsiekiera> daniel.siekiera@gmail.com
* 	Datum:			01. February 2018, 10:00 Uhr
*
*	Projekt:		Copyright 2018 by BigClick GmbH & Co.KG
* ----------------------------------------------------------------------------------- */

$_available_currencies = [
	// Digital
	['BTC', 'Bitcoin', 'digital'],
	['BCH', 'Bitcoin Cash', 'digital'],
	['DASH', 'DASH', 'digital'],
	['EOS', 'EOS', 'digital'],
	['ETH', 'Ethereum', 'digital'],
	['MIOTA', 'IOTA', 'digital'],
	['LTC', 'Litecoin', 'digital'], 
	['XMR', 'Monero', 'digital'],
	['XEM', 'NEM', 'digital'],
	['NEO', 'NEO', 'digital'],
	['XRP', 'Ripple', 'digital'],
	['XLM', 'Stellar Lumens', 'digital'],
	// Fiat
	['AFN', 'Afghan Afghani', 'fiat'],
	['ALL', 'Albanian Lek', 'fiat'],
	['DZD', 'Algerian Dinar', 'fiat'],
	['AOA', 'Angolan Kwanza', 'fiat'],
	['ARS', 'Argentine Peso', 'fiat'],
	['AMD', 'Armenian Dram', 'fiat'],
	['AWG', 'Aruban Florin', 'fiat'],
	['AUD', 'Australian Dollar', 'fiat'],
	['AZN', 'Azerbaijani Manat', 'fiat'],
	['BSD', 'Bahamian Dollar', 'fiat'],
	['BHD', 'Bahraini Dinar', 'fiat'],
	['BDT', 'Bangladeshi Taka', 'fiat'],
	['BBD', 'Barbadian Dollar', 'fiat'],
	['BYR', 'Belarusian Ruble', 'fiat'],
	['BZD', 'Belize Dollar', 'fiat'],
	['BMD', 'Bermudan Dollar', 'fiat'],
	['BTN', 'Bhutanese Ngultrum', 'fiat'],
	['BOB', 'Bolivian Boliviano', 'fiat'],
	['BAM', 'Bosnia-Herzegovina Convertible M', 'fiat'],
	['BWP', 'Botswanan Pula', 'fiat'],
	['BRL', 'Brazilian Real', 'fiat'],
	['GBP', 'British Pound Sterling', 'fiat'],
	['BND', 'Brunei Dollar', 'fiat'],
	['BGN', 'Bulgarian Lev', 'fiat'],
	['BIF', 'Burundian Franc', 'fiat'],
	['KHR', 'Cambodian Riel', 'fiat'],
	['CAD', 'Canadian Dollar', 'fiat'],
	['CVE', 'Cape Verdean Escudo', 'fiat'],
	['KYD', 'Cayman Islands Dollar', 'fiat'],
	['XOF', 'CFA Franc BCEAO', 'fiat'],
	['XAF', 'CFA Franc BEAC', 'fiat'],
	['XPF', 'CFP Franc', 'fiat'],
	['CLP', 'Chilean Peso', 'fiat'],
	['CNY', 'Chinese Yuan', 'fiat'],
	['COP', 'Colombian Peso', 'fiat'],
	['KMF', 'Comorian Franc', 'fiat'],
	['CDF', 'Congolese Franc', 'fiat'],
	['CRC', 'Costa Rican Colón', 'fiat'],
	['HRK', 'Croatian Kuna', 'fiat'],
	['CUC', 'Cuban Convertible Peso', 'fiat'],
	['CUP', 'Cuban Peso', 'fiat'],
	['CZK', 'Czech Republic Koruna', 'fiat'],
	['DKK', 'Danish Krone', 'fiat'],
	['DJF', 'Djiboutian Franc', 'fiat'],
	['DOP', 'Dominican Peso', 'fiat'],
	['XCD', 'East Caribbean Dollar', 'fiat'],
	['EGP', 'Egyptian Pound', 'fiat'],
	['ERN', 'Eritrean Nakfa', 'fiat'],
	['ETB', 'Ethiopian Birr', 'fiat'],
	['EUR', 'Euro', 'fiat'],
	['FKP', 'Falkland Islands Pound', 'fiat'],
	['FJD', 'Fijian Dollar', 'fiat'],
	['GMD', 'Gambian Dalasi', 'fiat'],
	['GEL', 'Georgian Lari', 'fiat'],
	['GHS', 'Ghanaian Cedi', 'fiat'],
	['GIP', 'Gibraltar Pound', 'fiat'],
	['XAU', 'Gold (troy ounce)', 'fiat'],
	['GTQ', 'Guatemalan Quetzal', 'fiat'],
	['GGP', 'Guernsey Pound', 'fiat'],
	['GNF', 'Guinean Franc', 'fiat'],
	['GYD', 'Guyanaese Dollar', 'fiat'],
	['HTG', 'Haitian Gourde', 'fiat'],
	['HNL', 'Honduran Lempira', 'fiat'],
	['HKD', 'Hong Kong Dollar', 'fiat'],
	['HUF', 'Hungarian Forint', 'fiat'],
	['ISK', 'Icelandic Króna', 'fiat'],
	['INR', 'Indian Rupee', 'fiat'],
	['IDR', 'Indonesian Rupiah', 'fiat'],
	['IRR', 'Iranian Rial', 'fiat'],
	['IQD', 'Iraqi Dinar', 'fiat'],
	['ILS', 'Israeli New Sheqel', 'fiat'],
	['JMD', 'Jamaican Dollar', 'fiat'],
	['JPY', 'Japanese Yen', 'fiat'],
	['JEP', 'Jersey Pound', 'fiat'],
	['JOD', 'Jordanian Dinar', 'fiat'],
	['KZT', 'Kazakhstani Tenge', 'fiat'],
	['KES', 'Kenyan Shilling', 'fiat'],
	['KWD', 'Kuwaiti Dinar', 'fiat'],
	['KGS', 'Kyrgystani Som', 'fiat'],
	['LAK', 'Laotian Kip', 'fiat'],
	['LBP', 'Lebanese Pound', 'fiat'],
	['LSL', 'Lesotho Loti', 'fiat'],
	['LRD', 'Liberian Dollar', 'fiat'],
	['LYD', 'Libyan Dinar', 'fiat'],
	['MOP', 'Macanese Pataca', 'fiat'],
	['MKD', 'Macedonian Denar', 'fiat'],
	['MGA', 'Malagasy Ariary', 'fiat'],
	['MWK', 'Malawian Kwacha', 'fiat'],
	['MYR', 'Malaysian Ringgit', 'fiat'],
	['MVR', 'Maldivian Rufiyaa', 'fiat'],
	['IMP', 'Manx pound', 'fiat'],
	['MRO', 'Mauritanian Ouguiya', 'fiat'],
	['MUR', 'Mauritian Rupee', 'fiat'],
	['MXN', 'Mexican Peso', 'fiat'],
	['MDL', 'Moldovan Leu', 'fiat'],
	['MNT', 'Mongolian Tugrik', 'fiat'],
	['MAD', 'Moroccan Dirham', 'fiat'],
	['MZN', 'Mozambican Metical', 'fiat'],
	['MMK', 'Myanma Kyat', 'fiat'],
	['NAD', 'Namibian Dollar', 'fiat'],
	['NPR', 'Nepalese Rupee', 'fiat'],
	['ANG', 'Netherlands Antillean Guilder', 'fiat'],
	['BYN', 'New Belarusian Ruble', 'fiat'],
	['TWD', 'New Taiwan Dollar', 'fiat'],
	['NZD', 'New Zealand Dollar', 'fiat'],
	['NIO', 'Nicaraguan Córdoba', 'fiat'],
	['NGN', 'Nigerian Naira', 'fiat'],
	['KPW', 'North Korean Won', 'fiat'],
	['NOK', 'Norwegian Krone', 'fiat'],
	['OMR', 'Omani Rial', 'fiat'],
	['PKR', 'Pakistani Rupee', 'fiat'],
	['PAB', 'Panamanian Balboa', 'fiat'],
	['PGK', 'Papua New Guinean Kina', 'fiat'],
	['PYG', 'Paraguayan Guarani', 'fiat'],
	['PEN', 'Peruvian Nuevo Sol', 'fiat'],
	['PHP', 'Philippine Peso', 'fiat'],
	['PLN', 'Polish Zloty', 'fiat'],
	['QAR', 'Qatari Rial', 'fiat'],
	['RON', 'Romanian Leu', 'fiat'],
	['RUB', 'Russian Ruble', 'fiat'],
	['RWF', 'Rwandan Franc', 'fiat'],
	['SHP', 'Saint Helena Pound', 'fiat'],
	['SVC', 'Salvadoran Colón', 'fiat'],
	['WST', 'Samoan Tala', 'fiat'],
	['STD', 'São Tomé and Príncipe Dobra', 'fiat'],
	['SAR', 'Saudi Riyal', 'fiat'],
	['RSD', 'Serbian Dinar', 'fiat'],
	['SCR', 'Seychellois Rupee', 'fiat'],
	['SLL', 'Sierra Leonean Leone', 'fiat'],
	['XAG', 'Silver (troy ounce)', 'fiat'],
	['SGD', 'Singapore Dollar', 'fiat'],
	['SBD', 'Solomon Islands Dollar', 'fiat'],
	['SOS', 'Somali Shilling', 'fiat'],
	['ZAR', 'South African Rand', 'fiat'],
	['KRW', 'South Korean Won', 'fiat'],
	['XDR', 'Special Drawing Rights', 'fiat'],
	['LKR', 'Sri Lankan Rupee', 'fiat'],
	['SDG', 'Sudanese Pound', 'fiat'],
	['SRD', 'Surinamese Dollar', 'fiat'],
	['SZL', 'Swazi Lilangeni', 'fiat'],
	['SEK', 'Swedish Krona', 'fiat'],
	['CHF', 'Swiss Franc', 'fiat'],
	['SYP', 'Syrian Pound', 'fiat'],
	['TJS', 'Tajikistani Somoni', 'fiat'],
	['TZS', 'Tanzanian Shilling', 'fiat'],
	['THB', 'Thai Baht', 'fiat'],
	['TOP', 'Tongan Paʻanga', 'fiat'],
	['TTD', 'Trinidad and Tobago Dollar', 'fiat'],
	['TND', 'Tunisian Dinar', 'fiat'],
	['TRY', 'Turkish Lira', 'fiat'],
	['TMT', 'Turkmenistani Manat', 'fiat'],
	['UGX', 'Ugandan Shilling', 'fiat'],
	['UAH', 'Ukrainian Hryvnia', 'fiat'],
	['AED', 'United Arab Emirates Dirham', 'fiat'],
	['USD', 'United States Dollar', 'fiat'],
	['UYU', 'Uruguayan Peso', 'fiat'],
	['UZS', 'Uzbekistan Som', 'fiat'],
	['VUV', 'Vanuatu Vatu', 'fiat'],
	['VEF', 'Venezuelan Bolívar Fuerte', 'fiat'],
	['VND', 'Vietnamese Dong', 'fiat'],
	['YER', 'Yemeni Rial', 'fiat'],
	['ZMW', 'Zambian Kwacha', 'fiat'],
	['ZWD', 'Zimbabwean Dollar', 'fiat']
];
